# Site settings
theme: jekyll-theme-cayman
title: 逝者如斯夫
email:
description: Community Site
baseurl:
url:
twitter_username:
github_username:  xiaoma20082008

# Build settings
markdown: kramdown
permalink: pretty
